import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

import {
  getStaticBlogPosts,
  mergeAndPaginateBlogPosts,
  normalizeBlogPageNumber,
  staticBlogPostToMarkdown,
} from "../../../libs/blog/static-posts";

describe("Pixal3D static blog catalog", () => {
  it("uses a topic-specific raster cover for every static article", () => {
    const posts = getStaticBlogPosts();

    expect(posts).toHaveLength(6);
    for (const post of posts) {
      expect(post.coverImage).toMatch(/^\/blog-covers\/[a-z0-9-]+\.webp$/);
    }
  });

  it("puts the model-uses article ahead of the five older guides", () => {
    const slugs = getStaticBlogPosts().map((post) => post.slug);

    expect(slugs).toEqual([
      "pixal3d-model-uses",
      "image-to-3d-model",
      "ai-3d-model-generator",
      "image-to-glb",
      "image-to-stl",
      "pixal3d-alternative",
    ]);
  });

  it("localizes the new article in English and Chinese", () => {
    const english = getStaticBlogPosts("en")[0];
    const chinese = getStaticBlogPosts("zh-CN")[0];

    expect(english.title).toBe("What Can You Do with a 3D Model Generated by Pixal3D?");
    expect(chinese.title).toBe("用 Pixal3D 生成 3D 模型后，可以用来做什么？");
    expect(chinese.excerpt).not.toBe(english.excerpt);
  });

  it("places the supplied AnyPoses figure immediately after the first linked use case", () => {
    for (const locale of ["en", "zh-CN"] as const) {
      const post = getStaticBlogPosts(locale)[0];
      const linkedUseIndex = post.sections.findIndex((section) => section.type === "linked-paragraphs");
      const linkedUse = post.sections[linkedUseIndex];
      const figure = post.sections[linkedUseIndex + 1];

      expect(linkedUseIndex).toBeGreaterThanOrEqual(0);
      expect(linkedUse).toMatchObject({
        type: "linked-paragraphs",
        paragraphs: [expect.arrayContaining([
          expect.objectContaining({ href: "https://anyposes.com" }),
        ])],
      });
      expect(figure).toMatchObject({
        type: "image",
        src: "/blog-covers/anyposes-custom-prop.png",
      });

      const markdown = staticBlogPostToMarkdown(post);
      expect(markdown.indexOf("(https://anyposes.com)")).toBeLessThan(
        markdown.indexOf("![", markdown.indexOf("(https://anyposes.com)")),
      );
    }
  });

  it("deduplicates, globally sorts, totals, and paginates combined posts once", () => {
    const databasePosts = [
      {
        id: "db-new",
        slug: "database-new",
        title: "Database new",
        excerpt: null,
        coverImage: null,
        publishedAt: "2026-10-01T00:00:00.000Z",
        authorName: "Editor",
      },
      {
        id: "db-duplicate",
        slug: "image-to-glb",
        title: "Duplicate must not win",
        excerpt: null,
        coverImage: null,
        publishedAt: "2026-11-01T00:00:00.000Z",
        authorName: "Editor",
      },
      {
        id: "db-old",
        slug: "database-old",
        title: "Database old",
        excerpt: null,
        coverImage: null,
        publishedAt: "2025-01-01T00:00:00.000Z",
        authorName: "Editor",
      },
    ];

    const firstPage = mergeAndPaginateBlogPosts(databasePosts, { locale: "en", page: 1, pageSize: 4 });
    const secondPage = mergeAndPaginateBlogPosts(databasePosts, { locale: "en", page: 2, pageSize: 4 });

    expect(firstPage).toMatchObject({ total: 8, totalPages: 2, page: 1, pageSize: 4 });
    expect(secondPage).toMatchObject({ total: 8, totalPages: 2, page: 2, pageSize: 4 });
    expect(firstPage.posts.map((post) => post.slug)).toEqual([
      "database-new",
      "pixal3d-model-uses",
      "image-to-3d-model",
      "ai-3d-model-generator",
    ]);
    expect([...firstPage.posts, ...secondPage.posts].filter((post) => post.slug === "image-to-glb")).toHaveLength(1);
    expect(secondPage.posts.at(-1)?.slug).toBe("database-old");
  });

  it("normalizes malformed pagination values to finite positive integers", () => {
    const result = mergeAndPaginateBlogPosts([], {
      page: Number.NaN,
      pageSize: Number.POSITIVE_INFINITY,
    });

    expect(result.page).toBe(1);
    expect(result.pageSize).toBe(12);
    expect(result.posts).toHaveLength(6);
    expect(Number.isFinite(result.totalPages)).toBe(true);
    expect(normalizeBlogPageNumber("abc", 1)).toBe(1);
    expect(normalizeBlogPageNumber("Infinity", 1)).toBe(1);
    expect(normalizeBlogPageNumber(-2, 1)).toBe(1);
  });

  it("wires shared static content into the Next.js blog", () => {
    const source = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8");
    const nextList = source("apps/next-app/app/[lang]/(root)/blog/page.tsx");
    const nextDetail = source("apps/next-app/app/[lang]/(root)/blog/[slug]/page.tsx");

    expect(nextList).toContain("mergeAndPaginateBlogPosts");
    expect(nextList).toContain("normalizeBlogPageNumber(pageParam, 1)");
    expect(nextDetail).toContain('section.type === "linked-paragraphs"');
    expect(nextDetail).toContain("<figure");
    expect(nextDetail).toContain('rel="noreferrer noopener"');
  });

  it("keeps the static catalog available when a database list query fails", () => {
    const source = (path: string) => readFileSync(resolve(process.cwd(), path), "utf8");
    const nextList = source("apps/next-app/app/[lang]/(root)/blog/page.tsx");

    expect(nextList).toContain("Database blog posts are unavailable; serving static posts only.");
    expect(nextList).toContain("return []");
    expect(nextList.indexOf("return []")).toBeLessThan(nextList.lastIndexOf("mergeAndPaginateBlogPosts"));
  });

  it("ships every cover and the unchanged supplied screenshot in Next.js", () => {
    const appRoot = "apps/next-app";
    const coverNames = getStaticBlogPosts().map((post) => post.coverImage?.split("/").at(-1));
    const expectedScreenshotHash = "5a41b46118f464ed12ad1fae43352d89991f79ab78d5d403db444dec56d8b994";

    for (const coverName of coverNames) {
      const cover = readFileSync(resolve(process.cwd(), appRoot, "public/blog-covers", coverName!));
      expect(cover.byteLength).toBeGreaterThan(100_000);
    }

    const screenshot = readFileSync(resolve(
      process.cwd(),
      appRoot,
      "public/blog-covers/anyposes-custom-prop.png",
    ));
    expect(createHash("sha256").update(screenshot).digest("hex")).toBe(expectedScreenshotHash);
  });
});
