import { getEnv, requireEnvForService } from './utils';

const privateOwnership = 'Asset ownership: private';

export const paymentConfig = {
  providers: {
    stripe: {
      get secretKey() {
        return requireEnvForService('STRIPE_SECRET_KEY', 'Stripe');
      },
      get publicKey() {
        return requireEnvForService('STRIPE_PUBLIC_KEY', 'Stripe');
      },
      get webhookSecret() {
        return requireEnvForService('STRIPE_WEBHOOK_SECRET', 'Stripe');
      },
    },
  },

  plans: {
    free: {
      provider: 'free',
      id: 'free',
      amount: 0,
      currency: 'USD',
      duration: { months: 1, type: 'recurring' },
      i18n: {
        en: {
          name: 'Free',
          description: 'No credit card needed.',
          duration: 'month',
          features: [
            '300 monthly credits',
            '1 concurrent task',
            '2 downloads per day',
            'Limited queue priority',
            'Asset ownership: shared sample license',
            'Advanced limits: 1024 resolution, 1024 texture, 100k mesh target',
          ],
        },
        'zh-CN': {
          name: 'Free',
          description: 'No credit card needed.',
          duration: 'month',
          features: [
            '300 monthly credits',
            '1 concurrent task',
            '2 downloads per day',
            'Limited queue priority',
            'Asset ownership: shared sample license',
            'Advanced limits: 1024 resolution, 1024 texture, 100k mesh target',
          ],
        },
      },
    },
    starterMonthly: {
      provider: 'stripe',
      id: 'starterMonthly',
      amount: 9,
      currency: 'USD',
      credits: 10000,
      duration: { months: 1, type: 'recurring' },
      stripePriceId: getEnv('STRIPE_PRICE_STARTER_MONTHLY') || getEnv('STRIPE_PRICE_STARTER') || 'price_starter_monthly_replace_me',
      i18n: {
        en: {
          name: 'Starter',
          description: 'Monthly credits for getting started with image-to-3D.',
          duration: 'month',
          features: [
            '10,000 monthly credits',
            '1 concurrent task',
            '20 downloads per day',
            'Standard queue priority',
            privateOwnership,
            'Advanced limits: 1024 resolution, 1024 texture, 150k mesh target',
          ],
        },
        'zh-CN': {
          name: 'Starter',
          description: 'Monthly credits for getting started with image-to-3D.',
          duration: 'month',
          features: [
            '10,000 monthly credits',
            '1 concurrent task',
            '20 downloads per day',
            'Standard queue priority',
            privateOwnership,
            'Advanced limits: 1024 resolution, 1024 texture, 150k mesh target',
          ],
        },
      },
    },
    creatorMonthly: {
      provider: 'stripe',
      id: 'creatorMonthly',
      amount: 19,
      currency: 'USD',
      credits: 30000,
      recommended: true,
      duration: { months: 1, type: 'recurring' },
      stripePriceId: getEnv('STRIPE_PRICE_CREATOR_MONTHLY') || getEnv('STRIPE_PRICE_CREATOR') || 'price_creator_monthly_replace_me',
      i18n: {
        en: {
          name: 'Creator',
          description: 'Higher texture detail and remeshing for asset creation.',
          duration: 'month',
          features: [
            '30,000 monthly credits',
            '2 concurrent tasks',
            'Unlimited downloads per day',
            'Priority queue',
            privateOwnership,
            'Advanced limits: 1024 resolution, 2048 texture, 200k mesh target',
            'Remesh enabled',
            'Saved model history',
          ],
        },
        'zh-CN': {
          name: 'Creator',
          description: 'Higher texture detail and remeshing for asset creation.',
          duration: 'month',
          features: [
            '30,000 monthly credits',
            '2 concurrent tasks',
            'Unlimited downloads per day',
            'Priority queue',
            privateOwnership,
            'Advanced limits: 1024 resolution, 2048 texture, 200k mesh target',
            'Remesh enabled',
            'Saved model history',
          ],
        },
      },
    },
    proMonthly: {
      provider: 'stripe',
      id: 'proMonthly',
      amount: 49,
      currency: 'USD',
      credits: 100000,
      duration: { months: 1, type: 'recurring' },
      stripePriceId: getEnv('STRIPE_PRICE_PRO_MONTHLY') || getEnv('STRIPE_PRICE_PRO') || 'price_pro_monthly_replace_me',
      i18n: {
        en: {
          name: 'Pro',
          description: 'Maximum detail settings for high-end GLB output.',
          duration: 'month',
          features: [
            '100,000 monthly credits',
            '4 concurrent tasks',
            'Unlimited downloads per day',
            'Maximum queue priority',
            privateOwnership,
            'Advanced limits: 1536 resolution, 4096 texture, 300k mesh target',
            'Remesh enabled',
            'Team-ready model history',
          ],
        },
        'zh-CN': {
          name: 'Pro',
          description: 'Maximum detail settings for high-end GLB output.',
          duration: 'month',
          features: [
            '100,000 monthly credits',
            '4 concurrent tasks',
            'Unlimited downloads per day',
            'Maximum queue priority',
            privateOwnership,
            'Advanced limits: 1536 resolution, 4096 texture, 300k mesh target',
            'Remesh enabled',
            'Team-ready model history',
          ],
        },
      },
    },
    starterYearly: {
      provider: 'stripe',
      id: 'starterYearly',
      amount: 72,
      currency: 'USD',
      credits: 10000,
      duration: { months: 12, type: 'recurring' },
      stripePriceId: getEnv('STRIPE_PRICE_STARTER_YEARLY') || 'price_starter_yearly_replace_me',
      i18n: {
        en: {
          name: 'Starter',
          description: 'Monthly credits for getting started with image-to-3D.',
          duration: 'year',
          features: [
            '10,000 monthly credits',
            '1 concurrent task',
            '20 downloads per day',
            'Standard queue priority',
            privateOwnership,
            'Advanced limits: 1024 resolution, 1024 texture, 150k mesh target',
          ],
        },
        'zh-CN': {
          name: 'Starter',
          description: 'Monthly credits for getting started with image-to-3D.',
          duration: 'year',
          features: [
            '10,000 monthly credits',
            '1 concurrent task',
            '20 downloads per day',
            'Standard queue priority',
            privateOwnership,
            'Advanced limits: 1024 resolution, 1024 texture, 150k mesh target',
          ],
        },
      },
    },
    creatorYearly: {
      provider: 'stripe',
      id: 'creatorYearly',
      amount: 156,
      currency: 'USD',
      credits: 30000,
      recommended: true,
      duration: { months: 12, type: 'recurring' },
      stripePriceId: getEnv('STRIPE_PRICE_CREATOR_YEARLY') || 'price_creator_yearly_replace_me',
      i18n: {
        en: {
          name: 'Creator',
          description: 'Higher texture detail and remeshing for asset creation.',
          duration: 'year',
          features: [
            '30,000 monthly credits',
            '2 concurrent tasks',
            'Unlimited downloads per day',
            'Priority queue',
            privateOwnership,
            'Advanced limits: 1024 resolution, 2048 texture, 200k mesh target',
            'Remesh enabled',
            'Saved model history',
          ],
        },
        'zh-CN': {
          name: 'Creator',
          description: 'Higher texture detail and remeshing for asset creation.',
          duration: 'year',
          features: [
            '30,000 monthly credits',
            '2 concurrent tasks',
            'Unlimited downloads per day',
            'Priority queue',
            privateOwnership,
            'Advanced limits: 1024 resolution, 2048 texture, 200k mesh target',
            'Remesh enabled',
            'Saved model history',
          ],
        },
      },
    },
    proYearly: {
      provider: 'stripe',
      id: 'proYearly',
      amount: 408,
      currency: 'USD',
      credits: 100000,
      duration: { months: 12, type: 'recurring' },
      stripePriceId: getEnv('STRIPE_PRICE_PRO_YEARLY') || 'price_pro_yearly_replace_me',
      i18n: {
        en: {
          name: 'Pro',
          description: 'Maximum detail settings for high-end GLB output.',
          duration: 'year',
          features: [
            '100,000 monthly credits',
            '4 concurrent tasks',
            'Unlimited downloads per day',
            'Maximum queue priority',
            privateOwnership,
            'Advanced limits: 1536 resolution, 4096 texture, 300k mesh target',
            'Remesh enabled',
            'Team-ready model history',
          ],
        },
        'zh-CN': {
          name: 'Pro',
          description: 'Maximum detail settings for high-end GLB output.',
          duration: 'year',
          features: [
            '100,000 monthly credits',
            '4 concurrent tasks',
            'Unlimited downloads per day',
            'Maximum queue priority',
            privateOwnership,
            'Advanced limits: 1536 resolution, 4096 texture, 300k mesh target',
            'Remesh enabled',
            'Team-ready model history',
          ],
        },
      },
    },
  },
} as const;
